#!/usr/bin/env python3
"""
scripts/generate-tier-cheatsheet.py — auto-generate TIERS.md from atom files.
"""

import os
import sys
import yaml
from pathlib import Path
from collections import defaultdict

ROOT = Path(__file__).resolve().parent.parent
ATOMS_DIR = ROOT / "atoms"

def main():
    tiers = defaultdict(list)
    
    for f in sorted(ATOMS_DIR.glob("*.yaml")):
        with open(f) as fh:
            data = yaml.safe_load(fh)
        tier = data.get('tier', 4)
        glyph = data['glyph']
        name = f.stem
        primary = data.get('semantic', {}).get('primary', '')
        tiers[tier].append((glyph, name, primary))
    
    lines = []
    lines.append("# TIERS.md")
    lines.append("")
    lines.append("Printable cheatsheet. Tier 0 fits on a phone screen. Tier 1 fits on a postcard.")
    lines.append("")
    lines.append("*Auto-generated by `scripts/generate-tier-cheatsheet.py`*")
    lines.append("")
    
    for tier in [0, 1, 2, 3, 4]:
        items = sorted(tiers.get(tier, []), key=lambda x: x[1])
        if not items:
            continue
        
        if tier == 0:
            lines.append("---")
            lines.append("")
            lines.append("## Tier 0 — Pocket (12 atoms)")
            lines.append("")
            lines.append("Memorize these. Cover ~80% of daily use.")
            lines.append("")
            lines.append("| Glyph | Atom | Primary Use |")
            lines.append("|-------|------|-------------|")
        elif tier == 1:
            lines.append("")
            lines.append("---")
            lines.append("")
            lines.append(f"## Tier 1 — Daily ({len(items)} atoms)")
            lines.append("")
            lines.append("Reach without thinking.")
            lines.append("")
            lines.append("| Glyph | Atom | Primary Use |")
            lines.append("|-------|------|-------------|")
        elif tier == 2:
            lines.append("")
            lines.append("---")
            lines.append("")
            lines.append(f"## Tier 2 — Workshop ({len(items)} atoms)")
            lines.append("")
            lines.append("Specialized, recallable.")
            lines.append("")
            lines.append("| Glyph | Atom | Primary Use |")
            lines.append("|-------|------|-------------|")
        elif tier == 3:
            lines.append("")
            lines.append("---")
            lines.append("")
            lines.append(f"## Tier 3 — Library ({len(items)} atoms)")
            lines.append("")
            lines.append("Need lookup. Not for production without justification.")
            lines.append("")
            lines.append("See `atoms/` directory for full metadata.")
        elif tier == 4:
            lines.append("")
            lines.append("---")
            lines.append("")
            lines.append(f"## Tier 4 — Archive ({len(items)} atoms)")
            lines.append("")
            lines.append("Searchable only. Not for production.")
            lines.append("")
            lines.append("See `atoms/archive/` directory.")
        
        if tier <= 2:
            for glyph, name, primary in items:
                lines.append(f"| {glyph} | {name} | {primary} |")
    
    lines.append("")
    output = "\n".join(lines)
    
    outpath = ROOT / "TIERS.md"
    with open(outpath, 'w') as f:
        f.write(output)
    
    print(f"  generated {outpath}")
    print(f"  Tier 0: {len(tiers[0])} atoms")
    print(f"  Tier 1: {len(tiers[1])} atoms")
    print(f"  Tier 2: {len(tiers[2])} atoms")
    if tiers[3]: print(f"  Tier 3: {len(tiers[3])} atoms")
    if tiers[4]: print(f"  Tier 4: {len(tiers[4])} atoms")

if __name__ == "__main__":
    main()
